[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
[build]
  publish = "public/"
  functions = "functions/"
  
# [[redirects]]
  # from = "/*"
  # to = "./functions/take-screenshot"
  # status = 200
